[functions]
    directory = "netlify/functions"

[[redirects]]
    from = "/api/menu"
    to = "/.netlify/functions/menu"
    status = 200

[[redirects]]
    from = "/api/order"
    to = "/.netlify/functions/order"
    status = 200

[[redirects]]
    from = "/api/order/*"
    to = "/.netlify/functions/order"
    status = 200